#!/bin/bash
# TODO: criar yml header para template para:
# - article
# - bibliography
# - other fichas
# connection: index cards that link ideas and sections of the work plan; 
# question: index cards dealing with how to confront a particular problem;
# recommendation: index cards that note ideas provided by others
# suggestions: for further developments

note_destination=${1:-"$NOTESIN"}

note_id="$(date +'%Y%m%d%H%M%S')"
note_ui_name="$note_id.md"

tmpdirectory=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
fleeting_dst="$tmpdirectory/$note_ui_name"

fleetinbox="$note_destination/$note_ui_name"

file_header=$(cat << EOF
---
title:
id: $note_id
type:
tags:
 -
---
EOF
)

echo "$file_header" > "$fleeting_dst"

nvim "$fleetinbox" -c "silent 0read $fleeting_dst" + 2>/dev/null
