#!/bin/bash -
# ZEx: Zettelkasten Explorer
# Original Author & date: <benevidesh, 2022-12-01>
#_________________________________________________________________________
PROGRAM=${0##*/}  # bash version of `basename`


# GLOBAL and constant variables
FILE_EXTENSION=".md"
FILTER_CMD="cut -d: -f1"

INITIAL_QUERY="^title"
GRP_PREFIX="grep -H -m 1 -in $INITIAL_QUERY *.md | cut -d: -f1,4 | sed 's/$FILE_EXTENSION:/ - /g;s/:title://' |  sed 's/  \+/ /g'"

#GRP_PREFIX_FLTR="$GRP_PREFIX {q} | while read file; do grep 'title' $file; done"
#GRP_PREFIX="rg --max-count 1 --line-number  --no-heading  --color=always --smart-case --glob '*.md'"

###########################################################################
# Main

# TODO: reload not with change but with pressing Enter (as search)
# ctrl-v: view

# Code...
    #fzf --bind "change:reload:sleep 0.1;($GRP_PREFIX {q} | cut -d: -f1,2,4) || true"
function matching_notes () {
    notes=$(grep -m 1 -ni ${1} *.md |  cut -d: -f1 | xargs grep -m 1 -H ^title: | sed 's/:title:/ - /g;s/.md//g;s/  \+/ /g')
    printf "%s\n" "${notes}"
}
export -f matching_notes

# Mappings
# ctrl-b: backlinks
# ctrl-a: id [address]
FZF_DEFAULT_COMMAND="$GRP_PREFIX  "\
        fzf --bind "change:reload:(matching_notes {q}) || true" \
                  --bind "ctrl-b:reload:(printf "%s\n" {} | cut -d' ' -f1 | xargs -I{} grep {} *.md | cut -d: -f1 | xargs grep -H ^title: | sed 's/:title:/ - /g;s/.md//g') || true" \
                  --disabled \
                  --style full \
                  --delimiter - \
                  --preview "[[ ! -z {} ]] && cat {1}$FILE_EXTENSION" \
                  --preview-window "~3" \
                  --bind 'ctrl-e:execute(printf "%s\n" {+} | cut -d" " -f1 | sed 's/$/.md/g' | xargs -I{} -o nvim --server "$NVIM_LISTEN_ADDRESS"  --remote $PWD/{})' \
                  --bind 'ctrl-o:execute-silent(printf "%s\n" {+} | cut -d" " -f1 | sed 's/$/.md/g' | xargs -I{} xdg-open $PWD/{} 2>/dev/null )' \
                  --bind 'enter:execute(printf "%s\n" {+} | cut -d" " -f1 | sed 's/$/.md/g' | xargs -o nvim  -c "silent bufdo grepadd ^'title'  %" )+reload:(matching_notes {q})' \
                  --bind "ctrl-a:execute(printf '%s\n' "{+}" | sed 's/\([0-9]\+\) - \(.*\)/\1/' | sed 's/\n/ /g' | xclip -selection clipboard)" \
                  --bind "ctrl-y:execute(printf '%s\n' "{+}" | sed 's/\([a-zA-Z]\+\?[0-9]\+\) - \(.*\)/[\2](\1.md)/' | xclip -selection clipboard)" \
                  --bind "backward-eof:reload(matching_notes .)"
